### ISSUE TITLE
Please add support for yaf, eaccelerator, lua and kafka 

### ISSUE THREAD

**Issue by libnux** [dmikusa-pivotal/cf-php-buildpack-binary-build-scripts#8]
We'll use these extensions in our project. Could you please add support for them? Many thanks.

**Comment by dmikusa-pivotal** [comment]
[Yaf](http://pecl.php.net/package/yaf) - I usually include the latest "stable" listing from PECL.  Is that OK here?  I see there are a couple beta releases too.

[eaccelerator](https://github.com/eaccelerator/eaccelerator/releases) - This seems really old.  I see it support 5.4.  Does it support 5.5 or 5.6?

[lua](http://pecl.php.net/package/lua) - I'm going to go with the latest "beta" here, because it seems to support more versions of PHP.  Let me know if you'd prefer the stable.

kafka - there seem to be several different clients for PHP.  Which one are you asking about specifically?

**Comment by libnux** [comment]
yaf - Yes
eaccelerator: we used it with PHP-5.4, and did not test 5.5/5.6. Cloud you please add support in 5.4 at least? 
lua - beta is OK
kafka - we use https://github.com/quipo/kafka-php, and it seems that it's written in pure PHP, and not needed to compile and install as an extension. Thus, it's not needed to include.

Many thanks for the great support!

**Comment by dmikusa-pivotal** [comment]
Here's an update:

  - yaf is done.  That was no problem.  Binaries should go out with the next release of PHP.

  - eaccelerator. I'm not going to add this.  It's too old and there are better more current options already supported.  That said, if you submitted a PR that doesn't break anything else, I'd accept it.

  - lua.  This was a huge PITA, but I was able to get it working.  Binaries should go out with the next release of PHP

  - kafka.  Excellent!  If that's pure PHP, then nothing is needed here.
