### ISSUE TITLE
Add the --with-config-file-scan-dir option for PHP builds

### ISSUE THREAD

**Issue by chregu** [dmikusa-pivotal/cf-php-buildpack-binary-build-scripts#9]
Me again ;)

It could be helpful to have the `--with-config-file-scan-dir` option compiled in (eg. set to `/home/vcap/app/php/etc/php.d/`)

And then adjust the installer in the php_buildpack to copy all .ini files in eg. .bp-options/php/php.d/ to that directory. This way I wouldn't have to copy the whole php.ini into .bp-options/php/php.ini if I want to adjust or add just one line.

See also http://php.net/php-ini-scanned-files

**Comment by dmikusa-pivotal** [comment]
I have really been trying to avoid compiling that into the binary because it would make the binary have specific knowledge about the environment.  When at all possible, I've been trying to keep things flexible especially with the binaries.

Would a `.user.ini` file work for your purposes here?  You can set most, but not all of the php.ini values in those.

    http://php.net/manual/en/configuration.file.per-user.php

**Comment by chregu** [comment]
I don't see the difference to already having `--with-config-file-path=/home/vcap/app/php/etc ` there and adding that. Not much more environment-specific stuff (especially since it's about the same: config files)

.user.ini could work as well. The only "problem" there is, if I want to use a different .user.ini in another environment (for whatever reason), I need to somehow change that .user.ini (or change it nefore deployment to CF). While having those options in .bp-config, it's clearly separated for CF specific stuff. 

And I can't change PHP_INI_SYSTEM config values this way (OTOH, not that many important ones are just "PHP_INI_SYSTEM" )

**Comment by dmikusa-pivotal** [comment]
>I don't see the difference to already having --with-config-file-path=/home/vcap/app/php/etc there and adding that.

I've been contemplating removing that.  I don't believe it's necessary because we set PHPRC in the environment.

>The only "problem" there is, if I want to use a different .user.ini in another environment (for whatever reason), I need to somehow change that .user.ini (or change it nefore deployment to CF).

I'm not sure I follow you here.  The .user.ini is pretty flexible.  It's like a .htaccess file and you can put them at various places throughout your project.  Like if you only want it to be set for a certain part of your PHP files (at least in a traditional PHP project, not sure how this would work with a MVC style app like Symfony).

>And I can't change PHP_INI_SYSTEM config values this way (OTOH, not that many important ones are just "PHP_INI_SYSTEM" )

I have on my todo list to add a configuration option to options.json which would let you configure the behavior of the php.ini file you include with your app.  The default behavior would be to completely overwrite it, while the alternate behavior would be to append to or update.  Not exactly sure how that would work, but any thoughts you have on that would be appreciated.

**Comment by chregu** [comment]
Sure, a way to append instead of replacing to php.ini would also solve my problem. Not sure right now what PHP does, when the same ini option is defined twice, which one it takes then, but that is easily testable.

Actually, I was thinking of exactly doing that with an .extension in my project, if the  --with-config-file-path doesn't make it to the project

> I'm not sure I follow you here. The .user.ini is pretty flexible. 

We use the same code base on different environments. Locally for development, on the CI for testing and on the live server. The needed .ini options may be different for each environment. When I add them now to .user.ini, I will have them on all envs (or disable it somehow on the other systems). So I'd prefer to have separate php.ini's for each environment (without having to fiddle around with those files during deployment)

**Comment by chregu** [comment]
Ok. I found an easy solution while looking through the PHP sources, there's the env variable

PHP_INI_SCAN_DIR

which allows one to set that directory for with-config-file-path

/* Check for PHP_INI_SCAN_DIR environment variable to override/set config file scan directory */
	
The only problem again is that you can't set that during the composer phase, maybe you could add that (and other PHP relevent env variables) to be allowed to also be used in the composer phase, but currently a minor issue, afaics (one example could be to increase the php memory_limit in case the scripts need a lot of memory)

**Comment by dmikusa-pivotal** [comment]
Interesting.  Gotta love [undocumented features](https://bugs.php.net/bug.php?id=67389) :)  

Assuming this works across versions 5.4, 5.5 & 5.6 it sounds like a good solution to me.  I'm not sure the build pack would use it directly, it'll probably keep using PHPRC.  However it'll work for users to further customize their PHP configurations.

I'll need to think more on the composer environment issue.  It's sounding more like we should be allowing users to configure the environment there too.  My current thought is to include the user configured environment options and then override a select set of them with build pack configuration, so that user's don't accidentally break things.

**Comment by dmikusa-pivotal** [comment]
I've reopened the [composer environment issue](https://github.com/cloudfoundry/php-buildpack/issues/34).  See that for more details.

I'm closing this one out.  I've removed '--with-config-file-path' for the reasons sited above.  It'll go out with the next build.

**Comment by chregu** [comment]
cool, thanks, looking forward to it
